name: CD

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deployToDev:
    name: Deploy to staging environment

    runs-on: ubuntu-latest

    env:
      AZURE_ACCOUNT_NAME: chaoyicicdtest@blackchoeyoutlook.onmicrosoft.com
      AZURE_ACCOUNT_PASSWORD: ${{secrets.AZURE_ACCOUNT_PASSWORD}}
      AZURE_SUBSCRIPTION_ID: ee788f54-a267-4d2f-bc9e-766957df46e5
      AZURE_TENANT_ID: f0348563-e707-449c-8685-c83d24eaf3c0
      M365_ACCOUNT_NAME: fxtest02@microsoft.com
      M365_ACCOUNT_PASSWORD: ${{secrets.M365_ACCOUNT_PASSWORD}}
      TEAMSFX_INSIDER_PREVIEW: true
    
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Provision
        uses: OfficeDev/teamsfx-cli-action@v1
        with:
          commands: provision
          subscription: ee788f54-a267-4d2f-bc9e-766957df46e5

      - name: Deploy
        uses: OfficeDev/teamsfx-cli-action@v1
        with:
          commands: deploy

      - name: Package
        uses: OfficeDev/teamsfx-cli-action@v1
        with:
          commands: package
      
      - name: Upload Teams App's package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: appPackage
          path: templates/appPackage/appPackage.zip